import React from 'react'
import { AbsoluteFill, Audio, staticFile } from 'remotion'
import { Showreel } from './Showreel'

/**
 * The same picture as `Showreel`, plus the synthesised sound design.
 * Kept as a separate composition so the site export stays silent and can't regress.
 * The WAV is generated by scripts/build-sound.ts from the same edit constants.
 */
export const ShowreelSound: React.FC = () => {
  return (
    <AbsoluteFill>
      <Showreel />
      <Audio src={staticFile('showreel-audio.wav')} />
    </AbsoluteFill>
  )
}
